CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "email" varchar(50) NOT NULL,
  "password" varchar(50) NOT NULL,
  "age" int NOT NULL,
  "rolId" int NOT NULL,
  "courseId" int NOT NULL
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "description" varchar(50),
  "teacher" varchar(20) NOT NULL,
  "levelId" int NOT NULL,
  "categoryId" int NOT NULL,
  "videoId" int NOT NULL
);

CREATE TABLE "Course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "url" varchar(20) NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(10)
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(10) NOT NULL
);

CREATE TABLE "Levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(10)
);

FOREIGN KEYS

ALTER TABLE "Users" ADD FOREIGN KEY ("rolId") REFERENCES "Roles" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("videoId") REFERENCES "Course_video" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("levelId") REFERENCES "Levels" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("categoryId") REFERENCES "Categories" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("courseId") REFERENCES "Courses" ("id");

REGISTROS
Tabla Users
INSERT INTO "Users" (name, email, password, age, "rolId", "courseId") VALUES ('Java D', 'java@gmail.com', '123456', '18', '3', '3');
INSERT INTO "Users" (name, email, password, age, "rolId", "courseId") VALUES ('Noah T', 'noah@gmail.com', '15987', '24', '2', '1');
INSERT INTO "Users" (name, email, password, age, "rolId", "courseId") VALUES ('Daniela D', 'dani@gmail.com', '123456', '22', '3', '2');
INSERT INTO "Users" (name, email, password, age, "rolId", "courseId") VALUES ('Lea D', 'lea@gmail.com', '123456', '18', '3', '2');

Tabla Courses
INSERT INTO "Courses" (title, description, teacher, "levelId", "categoryId", "videoId") VALUES ('Aprende Node', 'De cero a experto', 'Ian', '3', '2', '1');
INSERT INTO "Courses" (title, description, teacher, "levelId", "categoryId", "videoId") VALUES ('Aprende JS', 'De cero a experto', 'Ale', '1', '1', '3');
INSERT INTO "Courses" (title, description, teacher, "levelId", "categoryId", "videoId") VALUES ('Aprende REACT', 'De cero a experto', 'Dani', '2', '3', '2');

Tabla Categories
INSERT INTO "Categories" (name) VALUES ('Inglés', 'Español', 'Portugues');

Table Course_video
INSERT INTO "Roles" (name) VALUES ('Maestro', 'Admin', 'Estudiando');

Table Levels
INSERT INTO "Levels" (level) VALUES ('Basico', 'Intermedio', 'Avanzado');

Table Course_video
INSERT INTO "Course_video" (title, url) VALUES ('NodeJs', 'video1.com');
INSERT INTO "Course_video" (title, url) VALUES ('React', 'video2.com');
INSERT INTO "Course_video" (title, url) VALUES ('JavaScript', 'video3.com');

































